### ISSUE TITLE
Lobotimzed owl selector?

### ISSUE THREAD

**Issue by iamnewton** [AssemblerUI/assembler-layout#1]
``` css
* + * {
    margin-top: 1.5em;
}
```

> Assuming that your paragraphs’ font-size is 1 em and its line-height is 1.5, we just set a default margin of one line between all successive flow elements of all varieties occurring in any order.
## Book-Like Justified Paragraphs

``` css
p {
    text-align: justify;
}

p + p {
margin-top: 0;
text-indent: 2em;
}
```
## Compact Modules

``` css
.compact * + * {
    margin-top: 0.75em;
}
```
## Widgets with Positioning

``` css
.margins-off > * {
    margin-top: 0;
}
```

[Source](http://alistapart.com/article/axiomatic-css-and-lobotomized-owls)
